#Hand, left or right
hand: right

#Hand prefix, rh or lh. If this is set, ns must be used.
hand_id: &hand_id rh

#Serial number
rh_serial: &serial '1130'

#Ethernet port
rh__eth_port: eth0

#Robot description xacro
robot_description_file: hand.urdf.xacro

robot_description_path: /etc/shadow/right/sr-config/

#Set namespace, default is 'true' as it is required for bimanual and prefix
use_ns: True

#PWM control, default := False
pwm_control: False

#Default := False
use_sim_time: False

#Hand mapping and joint prefix, prefix must be set for lh_ or rh_
hand:
  mapping:
    *serial: *hand_id
  joint_prefix:
    *serial: rh_
